name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Get Datetime
      uses: ccccmagicboy/get_datetime@master
      id: datetime
      with:
        tz1: 'Asia'
        tz2: 'Jerusalem'

    - name: Replace string
      uses: MathieuSoysal/replace-string-in-file@v1.0.0
      with:
        file: src/app.ts
        old-string: "VERSION_PLACEHOLDER"
        new-string: ${{ steps.datetime.outputs.datetime_str }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: arieschwartzman/openaiassistant-api:latest

        
