name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Datetime
      uses: ccccmagicboy/get_datetime@master
      id: datetime

    - name: Replace string
      uses: thiagodnf/string-replacer@v1.0.2
      with:
        find: "VERSION_PLACEHOLDER"
        replace: ${{ steps.datetime.outputs.datetime_str }}

    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: arieschwartzman/openaiassistant-api:latest

        
